name: Playwright API Tests

# Trigger workflow on push and pull request to main branch
on:
  push:
    branches:
      - bookstore-automation
  pull_request:
    branches:
      - bookstore-automation

jobs:
  test:
    name: Run Playwright Tests
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Install Playwright browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # 5. Run your API tests
      - name: Run API tests
        run: npx playwright test --reporter=list